// <auto-generated />
using System;
using EngineIQ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EngineIQ.Infrastructure.Migrations
{
    [DbContext(typeof(EngineIQDbContext))]
    [Migration("20260504205612_Session5_1_FnResolveExcludeSuspended")]
    partial class Session5_1_FnResolveExcludeSuspended
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("file_path");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("message");

                    b.Property<string>("PrMergeStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pr_merge_status");

                    b.Property<string>("RuleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrainingFeaturesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("training_features_json");

                    b.Property<bool>("WasActioned")
                        .HasColumnType("boolean")
                        .HasColumnName("was_actioned");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_findings_job_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_findings_tenant_id_created_at");

                    b.HasIndex("TenantId", "JobId")
                        .HasDatabaseName("ix_findings_tenant_id_job_id");

                    b.ToTable("findings", "public");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.PrReviewJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("GithubDeliveryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("github_delivery_id");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pr_number");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pr_review_jobs");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_pr_review_jobs_repository_id");

                    b.HasIndex("TenantId", "GithubDeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ix_pr_review_jobs_tenant_id_github_delivery_id");

                    b.ToTable("pr_review_jobs", "public");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchitectureStyle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("architecture_style");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_indexed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_repositories");

                    b.HasIndex("TenantId", "FullName")
                        .IsUnique()
                        .HasDatabaseName("ix_repositories_tenant_id_full_name");

                    b.ToTable("repositories", "public");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ApiKeyHash")
                        .HasColumnType("bytea")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ConfigYaml")
                        .HasColumnType("text")
                        .HasColumnName("config_yaml");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureFlagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_flags_json");

                    b.Property<long?>("GitHubAppInstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_app_installation_id");

                    b.Property<string>("GitHubInstallState")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("git_hub_install_state");

                    b.Property<long?>("GitHubOrgId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_org_id");

                    b.Property<string>("GitHubOrgLogin")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("git_hub_org_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<byte[]>("WebhookSecretHash")
                        .HasColumnType("bytea")
                        .HasColumnName("webhook_secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("GitHubAppInstallationId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_git_hub_app_installation_id");

                    b.HasIndex("GitHubInstallState")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_git_hub_install_state");

                    b.ToTable("tenants", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            ConfigYaml = "# Billable default — replace github_app_installation_id when GitHub App is installed for this org.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GitHubAppInstallationId = 9000000000001L,
                            Name = "Billable",
                            Plan = "Growth",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.TenantMetric", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<double>("AvgReviewMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_review_ms");

                    b.Property<int>("PrsReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("prs_reviewed");

                    b.Property<decimal>("TokenCostZar")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("token_cost_zar");

                    b.Property<int>("ViolationsFound")
                        .HasColumnType("integer")
                        .HasColumnName("violations_found");

                    b.HasKey("TenantId", "Date")
                        .HasName("pk_tenant_metrics");

                    b.ToTable("tenant_metrics", "public");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.Finding", b =>
                {
                    b.HasOne("EngineIQ.Infrastructure.Persistence.Entities.PrReviewJob", "Job")
                        .WithMany("Findings")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_pr_review_jobs_job_id");

                    b.HasOne("EngineIQ.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_tenants_tenant_id");

                    b.Navigation("Job");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.PrReviewJob", b =>
                {
                    b.HasOne("EngineIQ.Infrastructure.Persistence.Entities.Repository", "Repository")
                        .WithMany("Jobs")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pr_review_jobs_repositories_repository_id");

                    b.HasOne("EngineIQ.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pr_review_jobs_tenants_tenant_id");

                    b.Navigation("Repository");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.Repository", b =>
                {
                    b.HasOne("EngineIQ.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany("Repositories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repositories_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.TenantMetric", b =>
                {
                    b.HasOne("EngineIQ.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_metrics_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.PrReviewJob", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.Repository", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("EngineIQ.Infrastructure.Persistence.Entities.Tenant", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
